# Generated by Django 6.0.2 on 2026-03-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('store', '0002_alter_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartitems',
            new_name='CartItem',
        ),
    ]
